-- AlterTable
ALTER TABLE "Favorites" ALTER COLUMN "id" SET DEFAULT 1,
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "albums" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "artists" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "tracks" SET DEFAULT ARRAY[]::TEXT[];
DROP SEQUENCE "Favorites_id_seq";
